window.STORE_PRODUCTS = [
  {
    "id": "gt7",
    "category": "ps",
    "name": "Gran Turismo 7",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 35000,
    "image": "images/psgt7.jpg",
    "description": "La experiencia definitiva de carreras en PS5, con autos increÃ­bles, conducciÃ³n realista y grÃ¡ficos espectaculares."
  },
  {
    "id": "cyberpunk-2077",
    "category": "ps",
    "name": "Cyberpunk 2077",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 32000,
    "image": "images/cyberps.jpg",
    "description": "Un mundo futurista enorme lleno de acciÃ³n, tecnologÃ­a, decisiones y misiones intensas en la ciudad de Night City."
  },
  {
    "id": "psplus-3meses",
    "category": "suscripciones",
    "name": "PS Plus 3 meses",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 35000,
    "image": "images/psplus.jpg",
    "description": "ðŸ”¹ Essentialâœ”ï¸ Juegos del mesâœ”ï¸ Juego online\n\nðŸ”¹ Extraâœ”ï¸ Juegos del mesâœ”ï¸ CatÃ¡logo de juegosâœ”ï¸ Juego online\n\nðŸ”¹ Deluxeâœ”ï¸ Juegos del mesâœ”ï¸ CatÃ¡logo de juegosâœ”ï¸ Juego onlineâœ”ï¸ Juegos exclusivos",
    "oldPrice": 45000
  },
  {
    "id": "paramount",
    "category": "suscripciones",
    "name": "Paramount",
    "tag": "OFERTA",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Paramount.jpg",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store.",
    "featured": true
  },
  {
    "id": "netflix-premium",
    "category": "suscripciones",
    "name": "Netflix Premium",
    "tag": "TOP VENTAS",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 7400,
    "image": "images/Netflix.jpg",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store.",
    "featured": true
  },
  {
    "id": "canva-pro-1-ano",
    "category": "suscripciones",
    "name": "Canva Pro 1 aÃ±o",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 45000,
    "image": "images/Canva.jpg",
    "description": "365 dias de acceso Premium con garantia oficial de 27 Store.",
    "oldPrice": 70000
  },
  {
    "id": "hbo-max",
    "category": "suscripciones",
    "name": "HBO Max",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Max.jpg",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "prime",
    "category": "suscripciones",
    "name": "Prime",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Prime.jpg",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "crunchyroll",
    "category": "suscripciones",
    "name": "Crunchyroll",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Crunchyroll.jpg",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "disney-premium",
    "category": "suscripciones",
    "name": "Disney+ Premium",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 5000,
    "image": "images/Disney.jpg",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "cyberpunk-2077-pc",
    "category": "juegos",
    "name": "Cyberpunk 2077",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 75000,
    "image": "images/Cyberpunk2077pc.jpg",
    "description": "Metete de lleno en Night City, una megalopolis futurista obsesionada con el poder y las modificaciones corporales.",
    "oldPrice": 90000,
    "featured": true
  },
  {
    "id": "ea-sports-fc-26",
    "category": "juegos",
    "name": "EA SPORTS FC 26",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 65000,
    "image": "images/EASPORTSFC26pc.jpg",
    "description": "La entrega mas reciente del simulador de futbol, con plantillas actualizadas y gameplay realista.",
    "oldPrice": 90000,
    "featured": true
  },
  {
    "id": "the-last-of-us-part-i",
    "category": "juegos",
    "name": "The Last Of Us Part I",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 65000,
    "image": "images/TheLastOfUsPartIpc.jpg",
    "description": "Acompana a Joel y Ellie en un viaje brutal de supervivencia por un mundo devastado.",
    "oldPrice": 90000,
    "featured": true
  },
  {
    "id": "resident-evil-4-2023",
    "category": "juegos",
    "name": "Resident Evil 4 (2023)",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 40000,
    "image": "images/ResidentEvil4 (2023)pc.jpg",
    "description": "El regreso de un clasico absoluto, recreado desde cero con graficos brutales y jugabilidad moderna."
  },
  {
    "id": "dead-by-daylight",
    "category": "juegos",
    "name": "Dead by Daylight",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/DeadbyDaylightpc.jpg",
    "description": "Terror multijugador asimetrico para jugar con amigos: un asesino contra cuatro sobrevivientes."
  },
  {
    "id": "assetto-corsa",
    "category": "juegos",
    "name": "Assetto Corsa",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 17000,
    "image": "images/AssettoCorsapc.jpg",
    "description": "Simulador de conduccion con fisica hiperrealista, circuitos escaneados con laser y precision total."
  },
  {
    "id": "dayz",
    "category": "juegos",
    "name": "DayZ",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 37000,
    "image": "images/DayZpc.jpg",
    "description": "Supervivencia extrema en un mundo abierto postapocaliptico infectado por zombies."
  },
  {
    "id": "ready-or-not",
    "category": "juegos",
    "name": "Ready or Not",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/ReadyorNotpc.jpg",
    "description": "Shooter tactico realista donde el trabajo en equipo y el equipamiento correcto son clave."
  },
  {
    "id": "gta-v-enhanced",
    "category": "juegos",
    "name": "GTA V Enhanced",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/GtaVEnhancedpc.jpg",
    "description": "La version definitiva del clasico de Rockstar, optimizada con graficos de nueva generacion."
  },
  {
    "id": "arc-raider",
    "category": "juegos",
    "name": "ARC Raider",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 65000,
    "image": "images/ARCRaiderpc.jpg",
    "description": "Shooter de extraccion en tercera persona con accion, recursos y maquinas ARC."
  },
  {
    "id": "assassins-creed-valhalla",
    "category": "juegos",
    "name": "Assassin's Creed Valhalla",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/AssassinsCreedValhallapc.jpg",
    "description": "Convertite en Eivor, lidera tu clan vikingo y conquista territorios en una aventura RPG enorme."
  },
  {
    "id": "red-dead-redemption-2",
    "category": "juegos",
    "name": "Red Dead Redemption 2",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 55000,
    "image": "images/RedDeadRedemption2pc.jpg",
    "description": "Una obra maestra de Rockstar en el salvaje oeste, con mundo abierto e historia memorable."
  },
  {
    "id": "ps-gow",
    "category": "ps",
    "name": "God of War RagnarÃ¶k",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 35000,
    "image": "images/gowrps.jpg",
    "description": "Una aventura Ã©pica junto a Kratos y Atreus, con combates impresionantes, mitologÃ­a nÃ³rdica y una historia llena de acciÃ³n."
  },
  {
    "id": "the-last-of-us-part",
    "category": "ps",
    "name": "The Last of Us Part I",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 40000,
    "image": "images/PSthelast.jpg",
    "description": "Una historia intensa de supervivencia, emociÃ³n y acciÃ³n en un mundo destruido, con grÃ¡ficos renovados y una experiencia cinematogrÃ¡fica brutal."
  },
  {
    "id": "rdr2",
    "category": "ps",
    "name": "Red Dead Redemption 2",
    "tag": "PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 25000,
    "image": "images/rdr2ps.jpg",
    "description": "Una obra maestra de mundo abierto ambientada en el viejo oeste, con una historia profunda, libertad total y una experiencia cinematogrÃ¡fica increÃ­ble."
  },
  {
    "id": "juego-ps-a-pedido",
    "category": "ps",
    "name": "PedÃ­ tu juego PS4/PS5",
    "tag": "A pedido",
    "type": "Cuenta",
    "stock": "A cotizar",
    "price": 0,
    "image": "images/atencion.jpg",
    "description": "Mandanos el tÃ­tulo, ediciÃ³n y consola. Te respondemos precio, stock y forma de activaciÃ³n."
  },
  {
    "id": "re-requiem-random-1-key",
    "category": "keys",
    "name": "RE Requiem Random 1 Key",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 7000,
    "image": "images/k1.jpg",
    "description": "Intenta conseguir Resident Evil con esta clave especial."
  },
  {
    "id": "random-vip-5-keys",
    "category": "keys",
    "name": "Random VIP 5 Keys",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 25000,
    "image": "images/k2.jpg",
    "description": "Al menos 2 juegos valen 30 euros y el resto valen 20 euros o mas."
  },
  {
    "id": "random-diamond-5-keys",
    "category": "keys",
    "name": "Random DIAMOND 5 Keys",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 20000,
    "image": "images/k3.jpg",
    "description": "Al menos 2 juegos valen 15 euros y el resto valen 5 euros o mas.",
    "oldPrice": 55000
  },
  {
    "id": "aaa-random-5-keys",
    "category": "keys",
    "name": "AAA Random 5 Keys",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/K4.jpg",
    "description": "5 llaves con juegos de presupuesto AAA garantizados.",
    "oldPrice": 70000
  },
  {
    "id": "tier-s-random-1-key",
    "category": "keys",
    "name": "TIER S Random 1 Key",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 17000,
    "image": "images/k5.jpg",
    "description": "Una llave maestra con un juego de maxima categoria Tier S."
  },
  {
    "id": "5-random-keys-grand",
    "category": "keys",
    "name": "5 Random Keys (Grand)",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/k6.jpg",
    "description": "5 keys aleatorias de Steam con juegos."
  },
  {
    "id": "5-random-keys-elite",
    "category": "keys",
    "name": "5 Random Keys (Elite)",
    "tag": "OFERTA",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/k7.jpg",
    "description": "5 keys aleatorias de Steam con juegos valorados en mas de 20 euros."
  },
  {
    "id": "1-key-random-goty",
    "category": "keys",
    "name": "1 Key Random (GOTY)",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/k8.jpg",
    "description": "Key aleatoria con tÃ­tulos destacados de juegos del aÃ±o."
  },
  {
    "id": "1-key-random-grand",
    "category": "keys",
    "name": "1 Key Random (Grand)",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 5000,
    "image": "images/k9.jpg",
    "description": "Key aleatoria con juego random."
  },
  {
    "id": "seguidores-ig",
    "category": "social",
    "name": "Seguidores IG",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F1.jpg",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "likes-ig",
    "category": "social",
    "name": "Likes IG",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2000,
    "image": "images/F2.jpg",
    "description": "Aumenta la interaccion de tus posts con likes reales. Minima compra 100."
  },
  {
    "id": "seguidores-tiktok",
    "category": "social",
    "name": "Seguidores TikTok",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F3.jpg",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "likes-tiktok",
    "category": "social",
    "name": "Likes TikTok",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2000,
    "image": "images/F4.jpg",
    "description": "Impulsa tus videos con likes de perfiles activos. Minima compra 100."
  },
  {
    "id": "seguidores-twitch",
    "category": "social",
    "name": "Seguidores Twitch",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F5.jpg",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "seguidores-kick",
    "category": "social",
    "name": "Seguidores Kick",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F6.jpg",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "suscriptores-youtube",
    "category": "social",
    "name": "Suscriptores Youtube",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/F7.jpg",
    "description": "Suscriptores reales para tu canal. Minima compra 100."
  },
  {
    "id": "likes-youtube",
    "category": "social",
    "name": "Likes Youtube",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2000,
    "image": "images/F8.jpg",
    "description": "Mejora el posicionamiento de tus videos con likes. Minima compra 100."
  }
];

window.STORE_COUPONS = {
  "27STORE": { "label": "27STORE", "percent": 10 },
  "AMIGO27": { "label": "AMIGO27", "percent": 15 },
  "STREAMING": { "label": "STREAMING", "percent": 5 },
  "MILOFF": { "label": "MILOFF", "amount": 1000 },
  "5000OFF": { "label": "5000OFF", "amount": 5000 }
};
