window.STORE_PRODUCTS = [
  {
    "id": "gt7",
    "category": "ps",
    "name": "Gran Turismo 7",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 35000,
    "image": "images/psgt7.png",
    "description": "La experiencia definitiva de carreras en PS5, con autos increíbles, conducción realista y gráficos espectaculares."
  },
  {
    "id": "cyberpunk-2077",
    "category": "ps",
    "name": "Cyberpunk 2077",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 32000,
    "image": "images/cyberps.png",
    "description": "Un mundo futurista enorme lleno de acción, tecnología, decisiones y misiones intensas en la ciudad de Night City."
  },
  {
    "id": "psplus-3meses",
    "category": "suscripciones",
    "name": "PS Plus 3 meses",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 35000,
    "image": "images/psplus.png",
    "description": "🔹 Essential✔️ Juegos del mes✔️ Juego online\n\n🔹 Extra✔️ Juegos del mes✔️ Catálogo de juegos✔️ Juego online\n\n🔹 Deluxe✔️ Juegos del mes✔️ Catálogo de juegos✔️ Juego online✔️ Juegos exclusivos",
    "oldPrice": 45000
  },
  {
    "id": "paramount",
    "category": "suscripciones",
    "name": "Paramount",
    "tag": "OFERTA",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Paramount.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store.",
    "featured": true
  },
  {
    "id": "netflix-premium",
    "category": "suscripciones",
    "name": "Netflix Premium",
    "tag": "TOP VENTAS",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 7400,
    "image": "images/Netflix.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store.",
    "featured": true
  },
  {
    "id": "canva-pro-1-ano",
    "category": "suscripciones",
    "name": "Canva Pro 1 año",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 45000,
    "image": "images/Canva.png",
    "description": "365 dias de acceso Premium con garantia oficial de 27 Store.",
    "oldPrice": 70000
  },
  {
    "id": "hbo-max",
    "category": "suscripciones",
    "name": "HBO Max",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Max.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "prime",
    "category": "suscripciones",
    "name": "Prime",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Prime.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "crunchyroll",
    "category": "suscripciones",
    "name": "Crunchyroll",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Crunchyroll.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "disney-premium",
    "category": "suscripciones",
    "name": "Disney+ Premium",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 5000,
    "image": "images/Disney.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "cyberpunk-2077-pc",
    "category": "juegos",
    "name": "Cyberpunk 2077",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 75000,
    "image": "images/Cyberpunk2077pc.png",
    "description": "Metete de lleno en Night City, una megalopolis futurista obsesionada con el poder y las modificaciones corporales.",
    "oldPrice": 90000,
    "featured": true
  },
  {
    "id": "ea-sports-fc-26",
    "category": "juegos",
    "name": "EA SPORTS FC 26",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 65000,
    "image": "images/EASPORTSFC26pc.png",
    "description": "La entrega mas reciente del simulador de futbol, con plantillas actualizadas y gameplay realista.",
    "oldPrice": 90000,
    "featured": true
  },
  {
    "id": "the-last-of-us-part-i",
    "category": "juegos",
    "name": "The Last Of Us Part I",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 65000,
    "image": "images/TheLastOfUsPartIpc.png",
    "description": "Acompana a Joel y Ellie en un viaje brutal de supervivencia por un mundo devastado.",
    "oldPrice": 90000,
    "featured": true
  },
  {
    "id": "resident-evil-4-2023",
    "category": "juegos",
    "name": "Resident Evil 4 (2023)",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 40000,
    "image": "images/ResidentEvil4 (2023)pc.png",
    "description": "El regreso de un clasico absoluto, recreado desde cero con graficos brutales y jugabilidad moderna."
  },
  {
    "id": "dead-by-daylight",
    "category": "juegos",
    "name": "Dead by Daylight",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/DeadbyDaylightpc.png",
    "description": "Terror multijugador asimetrico para jugar con amigos: un asesino contra cuatro sobrevivientes."
  },
  {
    "id": "assetto-corsa",
    "category": "juegos",
    "name": "Assetto Corsa",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 17000,
    "image": "images/AssettoCorsapc.png",
    "description": "Simulador de conduccion con fisica hiperrealista, circuitos escaneados con laser y precision total."
  },
  {
    "id": "dayz",
    "category": "juegos",
    "name": "DayZ",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 37000,
    "image": "images/DayZpc.png",
    "description": "Supervivencia extrema en un mundo abierto postapocaliptico infectado por zombies."
  },
  {
    "id": "ready-or-not",
    "category": "juegos",
    "name": "Ready or Not",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/ReadyorNotpc.png",
    "description": "Shooter tactico realista donde el trabajo en equipo y el equipamiento correcto son clave."
  },
  {
    "id": "gta-v-enhanced",
    "category": "juegos",
    "name": "GTA V Enhanced",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/GtaVEnhancedpc.png",
    "description": "La version definitiva del clasico de Rockstar, optimizada con graficos de nueva generacion."
  },
  {
    "id": "arc-raider",
    "category": "juegos",
    "name": "ARC Raider",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 65000,
    "image": "images/ARCRaiderpc.png",
    "description": "Shooter de extraccion en tercera persona con accion, recursos y maquinas ARC."
  },
  {
    "id": "assassins-creed-valhalla",
    "category": "juegos",
    "name": "Assassin's Creed Valhalla",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/AssassinsCreedValhallapc.png",
    "description": "Convertite en Eivor, lidera tu clan vikingo y conquista territorios en una aventura RPG enorme."
  },
  {
    "id": "red-dead-redemption-2",
    "category": "juegos",
    "name": "Red Dead Redemption 2",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 55000,
    "image": "images/RedDeadRedemption2pc.png",
    "description": "Una obra maestra de Rockstar en el salvaje oeste, con mundo abierto e historia memorable."
  },
  {
    "id": "ps-gow",
    "category": "ps",
    "name": "God of War Ragnarök",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 35000,
    "image": "images/gowrps.png",
    "description": "Una aventura épica junto a Kratos y Atreus, con combates impresionantes, mitología nórdica y una historia llena de acción."
  },
  {
    "id": "the-last-of-us-part",
    "category": "ps",
    "name": "The Last of Us Part I",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 40000,
    "image": "images/PSthelast.png",
    "description": "Una historia intensa de supervivencia, emoción y acción en un mundo destruido, con gráficos renovados y una experiencia cinematográfica brutal."
  },
  {
    "id": "rdr2",
    "category": "ps",
    "name": "Red Dead Redemption 2",
    "tag": "PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 25000,
    "image": "images/rdr2ps.png",
    "description": "Una obra maestra de mundo abierto ambientada en el viejo oeste, con una historia profunda, libertad total y una experiencia cinematográfica increíble."
  },
  {
    "id": "juego-ps-a-pedido",
    "category": "ps",
    "name": "Pedí tu juego PS4/PS5",
    "tag": "A pedido",
    "type": "Cuenta",
    "stock": "A cotizar",
    "price": 0,
    "image": "images/atencion.png",
    "description": "Mandanos el título, edición y consola. Te respondemos precio, stock y forma de activación."
  },
  {
    "id": "re-requiem-random-1-key",
    "category": "keys",
    "name": "RE Requiem Random 1 Key",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 7000,
    "image": "images/k1.png",
    "description": "Intenta conseguir Resident Evil con esta clave especial."
  },
  {
    "id": "random-vip-5-keys",
    "category": "keys",
    "name": "Random VIP 5 Keys",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 25000,
    "image": "images/k2.png",
    "description": "Al menos 2 juegos valen 30 euros y el resto valen 20 euros o mas."
  },
  {
    "id": "random-diamond-5-keys",
    "category": "keys",
    "name": "Random DIAMOND 5 Keys",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 20000,
    "image": "images/k3.png",
    "description": "Al menos 2 juegos valen 15 euros y el resto valen 5 euros o mas.",
    "oldPrice": 55000
  },
  {
    "id": "aaa-random-5-keys",
    "category": "keys",
    "name": "AAA Random 5 Keys",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/K4.png",
    "description": "5 llaves con juegos de presupuesto AAA garantizados.",
    "oldPrice": 70000
  },
  {
    "id": "tier-s-random-1-key",
    "category": "keys",
    "name": "TIER S Random 1 Key",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 17000,
    "image": "images/k5.png",
    "description": "Una llave maestra con un juego de maxima categoria Tier S."
  },
  {
    "id": "5-random-keys-grand",
    "category": "keys",
    "name": "5 Random Keys (Grand)",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/k6.png",
    "description": "5 keys aleatorias de Steam con juegos."
  },
  {
    "id": "5-random-keys-elite",
    "category": "keys",
    "name": "5 Random Keys (Elite)",
    "tag": "OFERTA",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/k7.png",
    "description": "5 keys aleatorias de Steam con juegos valorados en mas de 20 euros."
  },
  {
    "id": "1-key-random-goty",
    "category": "keys",
    "name": "1 Key Random (GOTY)",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/k8.png",
    "description": "Key aleatoria con títulos destacados de juegos del año."
  },
  {
    "id": "1-key-random-grand",
    "category": "keys",
    "name": "1 Key Random (Grand)",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 5000,
    "image": "images/k9.png",
    "description": "Key aleatoria con juego random."
  },
  {
    "id": "seguidores-ig",
    "category": "social",
    "name": "Seguidores IG",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F1.png",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "likes-ig",
    "category": "social",
    "name": "Likes IG",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2000,
    "image": "images/F2.png",
    "description": "Aumenta la interaccion de tus posts con likes reales. Minima compra 100."
  },
  {
    "id": "seguidores-tiktok",
    "category": "social",
    "name": "Seguidores TikTok",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F3.png",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "likes-tiktok",
    "category": "social",
    "name": "Likes TikTok",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2000,
    "image": "images/F4.png",
    "description": "Impulsa tus videos con likes de perfiles activos. Minima compra 100."
  },
  {
    "id": "seguidores-twitch",
    "category": "social",
    "name": "Seguidores Twitch",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F5.png",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "seguidores-kick",
    "category": "social",
    "name": "Seguidores Kick",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F6.png",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "suscriptores-youtube",
    "category": "social",
    "name": "Suscriptores Youtube",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/F7.png",
    "description": "Suscriptores reales para tu canal. Minima compra 100."
  },
  {
    "id": "likes-youtube",
    "category": "social",
    "name": "Likes Youtube",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2000,
    "image": "images/F8.png",
    "description": "Mejora el posicionamiento de tus videos con likes. Minima compra 100."
  }
];

window.STORE_COUPONS = {
  "27STORE": { "label": "27STORE", "percent": 10 },
  "AMIGO27": { "label": "AMIGO27", "percent": 15 },
  "STREAMING": { "label": "STREAMING", "percent": 5 },
  "MILOFF": { "label": "MILOFF", "amount": 1000 },
  "5000OFF": { "label": "5000OFF", "amount": 5000 }
};
