window.STORE_PRODUCTS = [
  {
    "id": "psplus-3meses",
    "category": "suscripciones",
    "name": "Ps Plus 3Meses",
    "tag": "Ps5/ps5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 35000,
    "image": "images/psplus.png",
    "description": "🔹 Essential✔️ Juegos del mes✔️ Juego online",
    "oldPrice": 45000
  },
  {
    "id": "paramount",
    "category": "suscripciones",
    "name": "Paramount",
    "tag": "OFERTA",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Paramount.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store.",
    "featured": true
  },
  {
    "id": "netflix-premium",
    "category": "suscripciones",
    "name": "Netflix Premium",
    "tag": "TOP VENTAS",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 7400,
    "image": "images/Netflix.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store.",
    "featured": true
  },
  {
    "id": "canva-pro-1-ano",
    "category": "suscripciones",
    "name": "Canva Pro 1 ano",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 45000,
    "image": "images/Canva.png",
    "description": "365 dias de acceso Premium con garantia oficial de 27 Store.",
    "oldPrice": 70000
  },
  {
    "id": "hbo-max",
    "category": "suscripciones",
    "name": "HBO Max",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Max.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "prime",
    "category": "suscripciones",
    "name": "Prime",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Prime.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "crunchyroll",
    "category": "suscripciones",
    "name": "Crunchyroll",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/Crunchyroll.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "disney-premium",
    "category": "suscripciones",
    "name": "Disney+ Premium",
    "tag": "Suscripciones",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 5000,
    "image": "images/Disney.png",
    "description": "30 dias de acceso Premium con garantia oficial de 27 Store."
  },
  {
    "id": "pragmata-deluxe",
    "category": "juegos",
    "name": "PRAGMATA Deluxe",
    "tag": "PC",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 35000,
    "image": "images/PCPRAG.png",
    "description": "✅ Recibís una cuenta de Steam lista para usar con el juego instalado.\n✅ Acceso ilimitado – Ingresá y jugá cuando quieras, sin restricciones de tiempo.\n✅ Progreso guardado – Tus partidas estarán siempre a salvo.\n✅ Tiempo de juego libre – Disfrutá sin límites ni interrupciones.",
    "oldPrice": 50000
  },
  {
    "id": "the-last-of-us",
    "category": "juegos",
    "name": "The Last of Us Bundle PC Steam",
    "tag": "PC",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 35000,
    "image": "images/PCTHE12.png",
    "description": "✅ Recibís una cuenta de Steam lista para usar con el juego instalado.\n✅ Acceso ilimitado – Ingresá y jugá cuando quieras, sin restricciones de tiempo.\n✅ Progreso guardado – Tus partidas estarán siempre a salvo.\n✅ Tiempo de juego libre – Disfrutá sin límites ni interrupciones.",
    "oldPrice": 90000,
    "bestSeller": true
  },
  {
    "id": "god-of-war-bundle",
    "category": "juegos",
    "name": "God of War Bundle",
    "tag": "PC",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 35000,
    "image": "images/PCWOG.png",
    "description": "✅ Recibís una cuenta de Steam lista para usar con el juego instalado.\n✅ Acceso ilimitado – Ingresá y jugá cuando quieras, sin restricciones de tiempo.\n✅ Progreso guardado – Tus partidas estarán siempre a salvo.\n✅ Tiempo de juego libre – Disfrutá sin límites ni interrupciones.",
    "oldPrice": 70000,
    "bestSeller": true
  },
  {
    "id": "ea-sports-fc-26",
    "category": "juegos",
    "name": "EA SPORTS FC 26",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 65000,
    "image": "images/EASPORTSFC26pc.png",
    "description": "La entrega mas reciente del simulador de futbol, con plantillas actualizadas y gameplay realista.",
    "oldPrice": 90000,
    "featured": true
  },
  {
    "id": "the-last-of-us-part",
    "category": "juegos",
    "name": "The Last Of Us Part I",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 65000,
    "image": "images/TheLastOfUsPartIpc.png",
    "description": "Acompana a Joel y Ellie en un viaje brutal de supervivencia por un mundo devastado.",
    "oldPrice": 90000,
    "featured": true
  },
  {
    "id": "resident-evil-4-2023",
    "category": "juegos",
    "name": "Resident Evil 4 (2023)",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 40000,
    "image": "images/ResidentEvil4 (2023)pc.png",
    "description": "El regreso de un clasico absoluto, recreado desde cero con graficos brutales y jugabilidad moderna."
  },
  {
    "id": "dead-by-daylight",
    "category": "juegos",
    "name": "Dead by Daylight",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/DeadbyDaylightpc.png",
    "description": "Terror multijugador asimetrico para jugar con amigos: un asesino contra cuatro sobrevivientes."
  },
  {
    "id": "assetto-corsa",
    "category": "juegos",
    "name": "Assetto Corsa",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 17000,
    "image": "images/AssettoCorsapc.png",
    "description": "Simulador de conduccion con fisica hiperrealista, circuitos escaneados con laser y precision total."
  },
  {
    "id": "dayz",
    "category": "juegos",
    "name": "DayZ",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 37000,
    "image": "images/DayZpc.png",
    "description": "Supervivencia extrema en un mundo abierto postapocaliptico infectado por zombies."
  },
  {
    "id": "ready-or-not",
    "category": "juegos",
    "name": "Ready or Not",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/ReadyorNotpc.png",
    "description": "Shooter tactico realista donde el trabajo en equipo y el equipamiento correcto son clave."
  },
  {
    "id": "gta-v-enhanced",
    "category": "juegos",
    "name": "GTA V Enhanced",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/GtaVEnhancedpc.png",
    "description": "La version definitiva del clasico de Rockstar, optimizada con graficos de nueva generacion."
  },
  {
    "id": "arc-raider",
    "category": "juegos",
    "name": "ARC Raider",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 65000,
    "image": "images/ARCRaiderpc.png",
    "description": "Shooter de extraccion en tercera persona con accion, recursos y maquinas ARC."
  },
  {
    "id": "assassins-creed-valhalla",
    "category": "juegos",
    "name": "Assassin's Creed Valhalla",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/AssassinsCreedValhallapc.png",
    "description": "Convertite en Eivor, lidera tu clan vikingo y conquista territorios en una aventura RPG enorme."
  },
  {
    "id": "red-dead-redemption-2",
    "category": "juegos",
    "name": "Red Dead Redemption 2",
    "tag": "PC",
    "type": "Key",
    "stock": "Disponible",
    "price": 55000,
    "image": "images/RedDeadRedemption2pc.png",
    "description": "Una obra maestra de Rockstar en el salvaje oeste, con mundo abierto e historia memorable."
  },
  {
    "id": "tomb-raider-definitive-edition-copia",
    "category": "ps",
    "name": "TOMB RAIDER: DEFINITIVE EDITION copia",
    "tag": "ps5/ps5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 10000,
    "image": "images/PSTOMB.jpg",
    "description": "Seguís a una joven Lara Croft en una isla llena de peligros, donde debe sobrevivir, explorar tumbas, resolver puzzles y enfrentarse a enemigos en intensas batallas. Acción, aventura y supervivencia en tercera persona."
  },
  {
    "id": "ps-gow",
    "category": "ps",
    "name": "God of War Ragnarök",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 35000,
    "image": "images/gowrps.png",
    "description": "Una aventura épica junto a Kratos y Atreus, con combates impresionantes, mitología nórdica y una historia llena de acción."
  },
  {
    "id": "resident-evil",
    "category": "ps",
    "name": "Resident Evil Remake Trilogy",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "DISPONIBLE",
    "price": 30000,
    "image": "images/PSREMAKETRI.png",
    "description": "Una colección que reúne los remakes de los clásicos juegos de terror y acción de Resident Evil, con gráficos modernizados, atmósfera intensa y jugabilidad mejorada"
  },
  {
    "id": "cyberpunk-2077-ps",
    "category": "ps",
    "name": "Cyberpunk 2077",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 32000,
    "image": "images/cyberps.png",
    "description": "Un mundo futurista enorme lleno de acción, tecnología, decisiones y misiones intensas en la ciudad de Night City."
  },
  {
    "id": "gt7",
    "category": "ps",
    "name": "Gran Turismo 7",
    "tag": "ps5/ps5",
    "type": "Cuenta",
    "stock": "Disponible",
    "price": 35000,
    "image": "images/psgt7.png",
    "description": "La experiencia definitiva de carreras en PS5, con autos increíbles, conducción realista y gráficos espectaculares."
  },
  {
    "id": "the-last-of-us-part",
    "category": "ps",
    "name": "The Last of Us Part I",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 40000,
    "image": "images/PSthelast.png",
    "description": "Una historia intensa de supervivencia, emoción y acción en un mundo destruido, con gráficos renovados y una experiencia cinematográfica brutal."
  },
  {
    "id": "the-last-of-us-part",
    "category": "ps",
    "name": "THE LAST OF US PART II",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 35000,
    "image": "images/PSTHELOUD2.png",
    "description": "Una aventura épica junto a Kratos y Atreus, con combates impresionantes, mitología nórdica y una historia llena de acción."
  },
  {
    "id": "nba-2k26",
    "category": "ps",
    "name": "NBA 2K26",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 22000,
    "image": "images/PSNBA.png",
    "description": "NBA 2K26 es el mejor simulador de básquetbol. Juegabilidad realista, modos como MyCAREER, MyTEAM y MyNBA, gráficos impresionantes y online. Perfecto para fans del NBA."
  },
  {
    "id": "ghost-of-yotei",
    "category": "ps",
    "name": "GHOST OF YOTEI",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 50000,
    "image": "images/PSGHOSTOFYOTEI.png",
    "description": "Ghost of Yōtei es un juego de acción y aventura de mundo abierto desarrollado por Sucker Punch. Secuela espiritual de Ghost of Tsushima, ambientada en el Japón de 1603 (norte de Ezo)."
  },
  {
    "id": "residen-evil-requiem",
    "category": "ps",
    "name": "RESIDEN EVIL REQUIEM",
    "tag": "PS4/PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 55000,
    "image": "images/PSRESIDENT.png",
    "description": "Seguís a la analista del FBI Grace Ashcroft y a Leon S. Kennedy en una aterradora investigación en las ruinas de Raccoon City. Terror, acción, escasez de recursos y una historia intensa que cierra varias tramas de la saga. Pura tensión y clásicos sustos de Resident Evil."
  },
  {
    "id": "rdr2",
    "category": "ps",
    "name": "Red Dead Redemption 2",
    "tag": "PS5",
    "type": "Cuenta",
    "stock": "Consultar stock",
    "price": 25000,
    "image": "images/rdr2ps.png",
    "description": "Una obra maestra de mundo abierto ambientada en el viejo oeste, con una historia profunda, libertad total y una experiencia cinematográfica increíble."
  },
  {
    "id": "re-requiem-random-1-key",
    "category": "keys",
    "name": "RE Requiem Random 1 Key",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 7000,
    "image": "images/k1.png",
    "description": "Intenta conseguir Resident Evil con esta clave especial."
  },
  {
    "id": "random-vip-5-keys",
    "category": "keys",
    "name": "Random VIP 5 Keys",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 25000,
    "image": "images/k2.png",
    "description": "Al menos 2 juegos valen 30 euros y el resto valen 20 euros o mas."
  },
  {
    "id": "random-diamond-5-keys",
    "category": "keys",
    "name": "Random DIAMOND 5 Keys",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 20000,
    "image": "images/k3.png",
    "description": "Al menos 2 juegos valen 15 euros y el resto valen 5 euros o mas.",
    "oldPrice": 55000
  },
  {
    "id": "aaa-random-5-keys",
    "category": "keys",
    "name": "AAA Random 5 Keys",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 30000,
    "image": "images/K4.png",
    "description": "5 llaves con juegos de presupuesto AAA garantizados.",
    "oldPrice": 70000
  },
  {
    "id": "tier-s-random-1-key",
    "category": "keys",
    "name": "TIER S Random 1 Key",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 17000,
    "image": "images/K5.png",
    "description": "Una llave maestra con un juego de maxima categoria Tier S."
  },
  {
    "id": "5-random-keys-grand",
    "category": "keys",
    "name": "5 Random Keys (Grand)",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/K6.png",
    "description": "5 keys aleatorias de Steam con juegos."
  },
  {
    "id": "5-random-keys-elite",
    "category": "keys",
    "name": "5 Random Keys (Elite)",
    "tag": "OFERTA",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/K7.png",
    "description": "5 keys aleatorias de Steam con juegos valorados en mas de 20 euros."
  },
  {
    "id": "1-key-random-goty",
    "category": "keys",
    "name": "1 Key Random (GOTY)",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 15000,
    "image": "images/K8.png",
    "description": "Key aleatoria con titulos destacados de juegos del ano."
  },
  {
    "id": "1-key-random-grand",
    "category": "keys",
    "name": "1 Key Random (Grand)",
    "tag": "Keys",
    "type": "Key",
    "stock": "Disponible",
    "price": 5000,
    "image": "images/K9.png",
    "description": "Key aleatoria con juego random."
  },
  {
    "id": "vistas-tiktok",
    "category": "social",
    "name": "Vistas Tiktok",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 1500,
    "image": "images/F11.png",
    "description": "Vistas para Tiktok. Minima compra 1000."
  },
  {
    "id": "espectadores-tw",
    "category": "social",
    "name": "Espectadores Twitch",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 3000,
    "image": "images/F9.png",
    "description": "Espectadores para twitch. Minima compra 10."
  },
  {
    "id": "seguidores-ig",
    "category": "social",
    "name": "Seguidores IG",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F1.png",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "espectadores-k",
    "category": "social",
    "name": "Espectadores Kick",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 3000,
    "image": "images/F10.png",
    "description": "Espectadores para Kick. Mínima compra 10."
  },
  {
    "id": "likes-ig",
    "category": "social",
    "name": "Likes IG",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2000,
    "image": "images/F2.png",
    "description": "Aumenta la interaccion de tus posts con likes reales. Minima compra 100."
  },
  {
    "id": "seguidores-tiktok",
    "category": "social",
    "name": "Seguidores TikTok",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F3.png",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "likes-tiktok",
    "category": "social",
    "name": "Likes TikTok",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2000,
    "image": "images/F4.png",
    "description": "Impulsa tus videos con likes de perfiles activos. Minima compra 100."
  },
  {
    "id": "seguidores-twitch",
    "category": "social",
    "name": "Seguidores Twitch",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F5.png",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "seguidores-kick",
    "category": "social",
    "name": "Seguidores Kick",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2500,
    "image": "images/F6.png",
    "description": "Seguidores de alta calidad. Minima compra 100."
  },
  {
    "id": "suscriptores-youtube",
    "category": "social",
    "name": "Suscriptores Youtube",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 4000,
    "image": "images/F7.png",
    "description": "Suscriptores reales para tu canal. Minima compra 100."
  },
  {
    "id": "likes-youtube",
    "category": "social",
    "name": "Likes Youtube",
    "tag": "Social",
    "type": "Servicio",
    "stock": "Disponible",
    "price": 2000,
    "image": "images/F8.png",
    "description": "Mejora el posicionamiento de tus videos con likes. Minima compra 100."
  }
];

window.STORE_COUPONS = {
  "27STORE": {
    "label": "27STORE",
    "percent": 10
  }
};
